### ISSUE TITLE
Improve how we communicate about the mathematics, protocol and benefits of use 

### ISSUE THREAD

**Issue by HenrikWM** [HenrikWM/anonymous-tokens#10]
In order to promote adoption and sell the idea which this repo and the Go-repo demonstrates usage of, we need to explain the benefits of "Privacy Pass" and anonymous tokens in the best possible way and prioritize work in this space.

**Comment by HenrikWM** [comment]
Specifically I think we should consider this scenario:

1) User reading a formula in code wants to understand its purpose
2) User clicks on a deep-link where the formula is used
3) User lands on a Wiki-page here on a section explaining the formula, its usage and where it fits in the bigger picture (protocol)

**Comment by martstr** [comment]
Consider done?

**Comment by HenrikWM** [comment]
Agree. Lets update the wiki when it needs to and continuously improve readme and related docs when we get new ideas for improvements.
