### ISSUE TITLE
Add test-coverage of the cryptography and protocol

### ISSUE THREAD

**Issue by HenrikWM** [HenrikWM/anonymous-tokens#11]
Implement a test-coverage of the different pieces involved in the protocol. Consider to start with unit-tests of the smaller components and then create integration-tests between these to verify end-to-end scenarios.

**Comment by tjesi** [comment]
The functions GenerateToken, RandomiseToken and VerifyToken must verify that input is correct, that is, that the ECPoint's are on the curve and that the curve is the correct curve. 

Useful functions might be `ECPoint ValidatePoint(BigInteger x, BigInteger y)` and `ECCurve Equals(ECCurve other)`.

**Comment by tjesi** [comment]
Function `HashToCurve( )` might return `null` in `VerifyToken` when computing `var T = HashToCurve(curve, t);`. Then `var V = T.Multiply(k);` will throw an exception.

**Comment by HenrikWM** [comment]
Should add tests to verify/confirm which pieces of the protocol can be replayed or not. A need from a system point of view is that I want to prevent an attacker, who has intercepted one of our messages, to be able to send the message again at a later point (replay-attack) which will lead to manipulating/corrupting sent messages

**Comment by tjesi** [comment]
That is a good point. In our setting, this means that `VerifyToken` checks if `t` is in the list of received tokens before it checks if it's a valid token. If it is not seen before, and it is valid, then it stores `t`  to prevent replay-attacks later.

**Comment by martstr** [comment]
Potential tests:
- Creating a token, signing it, randomising it and verifying it returns true
- The proof verification returns false if K != ecParameters.G.Multiply(k)
- The proof verification returns false if W != P.Multiply(k)
- PointIsValid on the result from HashToWeierstrassCurve is always true if != null

**Comment by tjesi** [comment]
Make sure that the random number generator returns independently uniformly random numbers every time it is used. Important for the privacy of the user, but essential for the token generator to keep the private key k private.

Make sure that PointIsValid return false whenever input is Infinity or on a different curve.

**Comment by HenrikWM** [comment]
Begun a draft-PR on #29 and pushed a few tests do you can see the general layout of unittests. Made a folder for integrationtests (several classes used to test a larger cooperation between them) and will extract this into a separate testproject later.

I've added some missing parameter-checks for ensuring points being on the curve.

Think we should consider using `IsValid()` on `ECPoint` to perhaps replace our `ECPointVerifier`, or atleast calling `IsValid()` on `ECPoint` instances plus checking that they're on the specified curve. Don't have to do this now but worth looking into for later.

With the current implementation of `VerifyToken()` we can't verify in tests:
> The proof verification returns false if K != ecParameters.G.Multiply(k)
> The proof verification returns false if W != P.Multiply(k)
those are calculations inside of `VerifyToken()` (not too sure about where the first one is from) and we don't have `K` or `P` available as parameters in the method. We might be able to do this as an integration-test from the outside by creating scenarios with input-values and check for expected outcomes (true/false) but we then also risk indirectly testing the existing `ECPointVerifier.PointIsValid`.

**Comment by martstr** [comment]
The way to test those other two would be to replace K and W with random points on the curve instead. Then it should be readily testable.

**Comment by HenrikWM** [comment]
#29 should "fix" this issue. Any other things we want can be new issues or just Pull Requests that explains what new coverage has been added.

**Comment by martstr** [comment]
Done?

**Comment by HenrikWM** [comment]
Yes vote to close this issue now. Test-coverage will be a natural PR talking point moving forwards. We should strive to have at least some coverage on new PRs coming in before we merge them in (where its reasonable of course)
