### ISSUE TITLE
Publish as nuget package(s)?

### ISSUE THREAD

**Issue by sindremb** [HenrikWM/anonymous-tokens#15]
To facilitate the reuse of this logic, it would be useful to publish it as one or more nuget-packages.

Do you think it should all be included in a single package, or be split in to one or more packages? Client and backend would need separate parts of this logic, and the nuget packages could then be split accordingly. Work on #3 should also reflect the wanted nuget-package structure.

**Comment by HenrikWM** [comment]
Sounds like good idea :) We really want to separate the library/protocol code where possible so that consuming projects only gets the bits they need for their work (i.e. separation of concerns and not bloating consumers with code in prod which will never be used)

Have added NuGet-package as a new item on the roadmap (on my current branch) and will split the class-library into 3 libraries (Initiator, TokenGenerator and TokenVerifier) and see how that looks.

Current work is continuing on #14 at the moment :)

**Comment by sindremb** [comment]
I'd be happy to help out with that, I can spare some time this weekend.

What do you think is a good split and names of the nuget packages? I am a bit hesitant to use Client and Server in the naming, but i struggle to find better terms. Something like the following packages:

AnonymousTokens.Client
AnonymousTokens.Server
AnonymousTokens.Core (if applicable)

**Comment by HenrikWM** [comment]
I've got a PR ready now (#20) for publishing the first 0.1.0 package of the library where it stands at the moment. Will test a release to NuGet.org later today or tomorrow :)

Yes you're on to something.

![image](https://user-images.githubusercontent.com/1481951/99720681-5f828f00-2aae-11eb-8cba-72b378b62d92.png)

The Initiator, TokenGenerator and TokenVerifier are the 3 separate pieces of the protocol so Initiator would be "Client". I think that one's OK.

TokenGenerator and TokenVerifier both are run on a backend "Server" and one requires both public and private key, and one just the private key. So they can be hosted together in the same API or split up into separate APIs, maybe makes little difference.

@tjesi @martstr What do you think about "Client" and "Server"? I think it makes things simpler from the implementor's point of view to think about this in this way. The metaphor of Client and Server matches our current sample project. We could even merge the two APIs to simplify things as both have access to the private key anyways.

**Comment by martstr** [comment]
> @tjesi @martstr What do you think about "Client" and "Server"? I think it makes things simpler from the implementor's point of view to think about this in this way. The metaphor of Client and Server matches our current sample project. We could even merge the two APIs to simplify things as both have access to the private key anyways.

Fair enough. It could in principle be used at the same server in other applications, which is the idea for Privacy Pass anyway.

**Comment by tjesi** [comment]
Splitting it onto two packages AnonymousTokens.Client and AnonymousTokens.Server makes sense. As @martstr said: both TokenGenerator and TokenVerifier could be the same server (we are implicitly assuming this in our application, even though it's implemented as two different "programs", as our protocol deals with the potential problem where TokenGenerator and TokenVerifier shares information). 

As the public key can be computed directly from the secret key, it doesn't make any difference if both or neither of TokenGenerator and TokenVerifier has access to the public key, as long as they have access to the secret key. It makes sense to merge those into one API.

**Comment by HenrikWM** [comment]
Had a stab at this now. See #31 

Any input @sindremb ? :)

**Comment by HenrikWM** [comment]
Closing as we've landed on 3 separate NuGet packages in the end for Core, Client and Serve 👍
